### ISSUE TITLE
How can I get the most rated posts?

### ISSUE THREAD

**Issue by asfarmed** [blaz-blazer/rate-my-post#18]
Hi 
Is there a possibility to display the most rated posts on the site?

**Comment by blaz-blazer** [comment]
Hi there, 

A bit late but nevertheless. You can use: 
rmp_get_top_rated_posts( $max_posts, $required_rating, $required_votes ) function. 

More about this in the [docs](https://blazzdev.com/documentation/rate-my-post-documentation/#global-functions). 

Regards,
Blaz
