### ISSUE TITLE
Negative vote is submitted without feedback when its enabled

### ISSUE THREAD

**Issue by lopesgon** [blaz-blazer/rate-my-post#32]
## Context

When the feedback boolean "Show feedback widget if rating is negative" is enabled, we expect that the feedback is mandatory to vote but we can still vote without submitting any feedback.

### Steps to reproduce

1. Add a negative feedback to any post
2. Refresh page without submitting the feedback
3. Vote is considered and feedback isn't required at all

## Expected

When the feedback boolean is True, a vote below the positiveThreshold must be submitted only by feedback submit button.

**Comment by blaz-blazer** [comment]
Hi @lopesgon, 

That is expected behavior. The feedback is optional in case of a negative vote. Mandatory feedback should be an extra feature and is on to-do list. However, I do not have time to add it at the moment. 

Regards,
Blaz

**Comment by lopesgon** [comment]
Hi @blaz-blazer ,

Do you accept external contribution to your repo ? 

Maybe I take some time to implement this feature if you are ok, it would include the following specs (please correct them if you are open to external contribution).

### Specifications

* Admin panel will add a new property to force feedback, two options:
  * Option 1: new toggle force feedback
  * Option 2: existing toggle becomes a radio button choice with three options: No, Feedback, Force Feedback
* New REST endpoint to consume POST with rate and feedback all together
* When ForceFeedback is enabled a rating that matches feedback trigger will mount the feedback component 
* When feedback is submitted then rating and feedback are submitted in a single payload

### Notes
* When Prevent Accidental Mode is enabled it must always be shown before the Feedback evaluation

**Comment by blaz-blazer** [comment]
Hi @lopesgon, 

I'm of course opened to external contributions. However, is it possible that you write JS without jQuery? The thing is that I have two pull requests for removing jquery pending at the momment (https://github.com/blaz-blazer/rate-my-post/pull/33 and https://github.com/blaz-blazer/rate-my-post/pull/25). Therefore, any code that uses jQuery won't be useful in the future. 

Specifications sound good. I would go with Option 1 for admin panel. Let me know if you need anything from me. 

Thanks for your interest in the plugin.

Best regards,
Blaz
