### ISSUE TITLE
Custom rating elements

### ISSUE THREAD

**Issue by Nuruddinjr** [blaz-blazer/rate-my-post#7]
Hi, How can I add custom elements for rating. I would like to add numbers in a circle if possible

**Comment by blaz-blazer** [comment]
Hi @Nuruddinjr, 

the best way to do this, is to create a custom template which overrides the default template. More about custom templates [here](https://blazzdev.com/documentation/rate-my-post-documentation/#templates). 

Regards,
Blaz
